### ISSUE TITLE
[epic] Research viz libraries with strong focus on line charts

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/dpr-api#106]
We are focusing on line charts since by far the most common and in the spirit of doing one thing (very) well. Later we can look at other charts at least to start with.

In progress at: https://github.com/rgrp/line-charts

* [x] Research libraries https://github.com/rgrp/line-charts/issues/1 [epic]
* [x] Try out shortlist - https://github.com/rgrp/line-charts/issues/11 [epic]

**Comment by anuveyatsu** [comment]
FIXED. https://github.com/rgrp/line-charts
