### ISSUE TITLE
[signup] Test end to end

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/dpr-api#11]
Test end to end with mocking of external provider parts

- Start at moment where callback from auth provider to our app
- Check local on user stuff
- Check we get redirected to dashboard

**Comment by zelima** [comment]
Fixed with the latest commit

**Comment by zelima** [comment]
@kittdotech @subhankarb Think this is fixed with latest commit. Could you please confirm and close?

**Comment by rgrp** [comment]
FIXED.
