### ISSUE TITLE
Validate metadata in data packages

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#125]
We need to validate datapackage metadata before pushing to bit storage

Use: https://github.com/frictionlessdata/datapackage-py#validating-a-data-package

One issue is that we have package names like: `{publisher}/{name}` - that will violdate current dp py validator. /cc @pwalsh what do we want to do about this??

NOTE: we won't validate data - this is just about metadata. That would happen, if it did, async and elsewhere in system using goodtables.

**Comment by pwalsh** [comment]
@subhankarb ( cc @rgrp ) you could do a PR on https://github.com/frictionlessdata/schemas/blob/master/definitions.json#L59 to allow `/`.

**Comment by rgrp** [comment]
@pwalsh that was my plan but need a change in the DP spec right 😉

**Comment by rufuspollock** [comment]
Will not happen this sprint.

**Comment by Fak3** [comment]
@subhankarb I am confused by what you said in the issue description:
> NOTE: we won't validate data - this is just about metadata.

So is this issue about validating metadata (datapackage.json) or the resources data?

**Comment by Fak3** [comment]
Ok, renamed and clarifed the issue desctription. (this is for metadata only)

**Comment by rufuspollock** [comment]
WONTFIX. We won't take data package json over the API but straight into bitstore. if we do validate we'll do this on import form bitstore to main database.
