### ISSUE TITLE
Import all core data package datasets from data.okfn.org

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#129]
All core datasets from http://data.okfn.org/data/ live here! List is at: https://github.com/datasets/registry/blob/master/core-list.txt

- [x] User called `core`
  - Publisher called `/core`
- [x] Script to automate publishing using dpm-py
  - [x] Automate for one data package in a git repo given the git url
     - [x] Clone the git repo locally (automate that)
     - [x] Use dpmpy publish to publish to our staging site
  - [x] Do it for everything in https://github.com/datasets/registry/blob/master/core-list.txt
- [ ] Check all graphs - either fix graphs upstream or implement our recline auto conversion 😉 

This script should live in dpm-py.

For later:

Automated process for importing datasets from github based on each github push :wink:  - see https://github.com/frictionlessdata/project/issues/238 (replacing CKAN with the DPR)

**Comment by subhankarb** [comment]
The core data packages is getting pushed under admin user. Have to change it to core user

**Comment by subhankarb** [comment]
Fixed

**Comment by rufuspollock** [comment]
This is great. In future recommend we "eat our own dogfood" and use the existing purge command.
