### ISSUE TITLE
Get a nice URL for staging app

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#135]
To do this we need to link a custom domain to API-Gateway generated endpoint we get from Zappa.

We are going with **option 2** below as we don't want to register with route 53.

Best walkthrough is: https://www.pandastrike.com/posts/20160613-ssl-cert-aws-api-gateway-zerossl-letsencrypt

* [x] Get certificate via zerossl @subhankarb 
  * [x] Generating The CSR
  * [x] Apply For A Cert
    * [x] Prove we own the domain with DNS @rufuspollock
* [x] Add CERT to API Gateway (automate this?) @subhankarb 
* [x] Get cloudfront host @subhankarb 
* [x] CNAME domain to cloudfront host @rufuspollock

## Options

**Option 1:**

- Create DNS in route53 [Need to buy this from route53 console] - TODO: cost summary. $12 for domain + $0.50 a month plus more ...  [Route 53 pricing][53-pricing] - may be as much as $100 a year
- Zappa can automatically link to this - https://github.com/Miserlou/Zappa/blob/master/docs/domain_with_free_ssl_dns.md

[53-pricing]: https://aws.amazon.com/route53/pricing/

**Option 2:**

Zappa docs for this: https://github.com/Miserlou/Zappa/blob/master/docs/domain_with_free_ssl_http.md

A good walkthrough: https://www.pandastrike.com/posts/20160613-ssl-cert-aws-api-gateway-zerossl-letsencrypt

Amazon doc: http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html

- Have a domain registered
- Get a PEM-encoded SSL certificate for your custom domain name from a certificate authority. This can be done by ```zerossl` using ```letsencrypt``` - see https://www.pandastrike.com/posts/20160613-ssl-cert-aws-api-gateway-zerossl-letsencrypt
  1. Certificate private key
  2. Certificate body
  3. Certificate chain
- Manually or [programatically][boto-apig] create custom domain in API Gateway
- Map custom domain to cloudfront distribution point
  - Requires cloudfront distribution point which you then enter in your DNS provider

[boto-apig]: http://boto3.readthedocs.io/en/latest/reference/services/apigateway.html#APIGateway.Client.create_domain_name

**NOTE: all this info should be included in documentation for this function in our dpr-deploy code ;-)**

Once these are created we can link custom domain in API Gateway.

**Comment by subhankarb** [comment]
Fixed

**Comment by pwalsh** [comment]
what is the URL?

**Comment by zelima** [comment]
URL for staging website: https://staging.datapackaged.com/

**Comment by rufuspollock** [comment]
@subhankarb please take note of this little thread. When you close as FIXED it is good to offer a short summary of what has happened. In this case the obvious thing would have been:

```
FIXED. See {insert url of staging site}.
```
