### ISSUE TITLE
[js] React graph view for vega-lite

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#136]
Inline vega-lite

* [x] Create fixture data package to work with
  * [x] Data Package with resource data but we will ignore the resource data for now! Write out a vega-lite view with the data inlined as values ... 
* [x] Create a simple react view that renders this graph using just the vega-lite with inlined data
  * [x] add vega-lite libs
  * [x] write code to link together - should be super simple

Add support for `dataSource` - i.e. no inline data and injecting data from the data package resource

* [x] New fixture - without inline data and dataSource e.g. `/fixtures/dp1/` - https://github.com/frictionlessdata/datapackage-render-js/tree/master/test/data/dp1
* [x] Support dataSource but just convert to a url to data path (don't inject values)
  * i.e. dataSource: { resource: X } with resource X having { path: abc } gets injected into vega lite as data: { url: abc }
  * Look at - may be useful https://github.com/frictionlessdata/datapackage-js

```
var dp = new DataPackage(dpJson)
// path in resource is 'data.csv' but you loaded it from /fixtures/dp1/ so full path is fixtures/dp1/data.csv
var path = dp.resource[0].getResourcePath()
var myvegaspec = dp.views[0].spec; // probably want deep copy here
myvegaspec['data'] = {
    "url": path
  }
```

Plan for how we would switch this out for injecting the API url in the dpr app (will be separate issue):

* Switch out the local url for a function (which we will set to generate the API url in the real app!) i.e. ```/api/package/{blah}/{package}/r/{id}.json```

**Comment by anuveyatsu** [comment]
FIXED. Commit for supporting dataSource: https://github.com/frictionlessdata/dpr-js/commit/876c70e169431af160bfcc927835221d7a4b56cc
See entire repo: https://github.com/frictionlessdata/dpr-js
