### ISSUE TITLE
[js] Refactor JS for DP View page to use React

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#137]
What do we need to do:

> Get main site working with new react code

=>

* [x] Refactor JS "app" code in current "api" app in [static/js in dpr-api][current-js] into react-style code in our dpr-js repo - https://github.com/frictionlessdata/dpr-js/issues/12
 * [ ] Refactor main Flask app to use dpr-js

### Refactoring the Flask App

* submodule dpr-js repo into the static directory e.g. at `/app/static/dpr-js/`
* Delete current import of JS in [base.html template](https://github.com/frictionlessdata/dpr-api/blob/master/app/templates/base.html)
* Include our script `bundle.js` in [dataset.html][]

  ```javascript=
  {% block script %}
  <script>....</script{%>
  {% endblock %}
  ```
* Tweak our js app to bind to the right elements in our DOM ... 

[current-js]: https://github.com/frictionlessdata/dpr-api/tree/master/app/static/js

**Comment by subhankarb** [comment]
the sub-module is not working in travis

**Comment by rufuspollock** [comment]
@subhankarb is the sub-module issue now solved?

**Comment by subhankarb** [comment]
@rufuspollock yah it is working .... that day the first build failed .... but right now it is working.

**Comment by rufuspollock** [comment]
FIXED.
