### ISSUE TITLE
[publish] Test end to end

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#15]
- [x] Get a token using username + secret
- [x] Post metadata -> success
- [x] Get s3 upload for a data file
- [x] post data file => success

**Comment by zelima** [comment]
Closing as all are checked

**Comment by rgrp** [comment]
I do not think we have an end to end test - just tests of each part. This can be quite a small test but it should walk all the way through i think.

**Comment by kittdotech** [comment]
Done End to End Test for publish Flow.

**Comment by rgrp** [comment]
@subhankarb can you take a look to make sure this is really complete as per discussion on last sprint review meeting.

**Comment by rgrp** [comment]
@subhankarb did you get a chance to make the improvements here?

**Comment by subhankarb** [comment]
Fixed

**Comment by rufuspollock** [comment]
@subhankarb when you fix can you reference commit or similar (if that is not already shown in the issue).
