### ISSUE TITLE
S3 object level permission to read data

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#157]
Right now we do not have object level permission to read data publicly. Do we need this object level permission to read for every one?

**Comment by rufuspollock** [comment]
@subhankarb yes - we should have object level to read all stuff in s3 if the data package is public (i.e. not private).

**Comment by rufuspollock** [comment]
@subhankarb this wants to get set in S3 as we want people to direct access to objects in the s3 bucket if they are associated with a public data package (and not have to go through our API to get access).
