### ISSUE TITLE
Access-Control-Allow-Origin header for s3 request from dpr-js

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#158]
We need to add ```Access-Control-Allow-Origin``` in request header from dpr-js. else we are facing this issue: 
``` No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://*.*.*.*:5000' is therefore not allowed access.```

**Comment by anuveyatsu** [comment]
@subhankarb I think this is due to server's permission. If we send a request from localhost it is a Cross-Origin Request and it should be allowed on remote resource. When it is deployed it should not throw this error.

**Comment by subhankarb** [comment]
@anuveyatsu right we have to set CORS at s3 bucket
```
    <CORSRule>
        <AllowedOrigin>http://127.0.0.1:5000</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
```
Fixed

**Comment by rufuspollock** [comment]
@subhankarb is setting this part of the automated deploy? We should avoid doing things manually - and if we do make sure we get it back into the automated system.
