### ISSUE TITLE
Should return aws s3 link for object from back end

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#159]
Right now from ```datapackage_show``` api we are returning only key of the object like : ```metadata/core/demo-package/_v/latest/datapackage.json```, but we are not sending any other s3 related data like ```bucket name``` or send pre-signed url for reading the data

**Comment by rufuspollock** [comment]
@subhankarb can you explain *why* we would want this additional info e.g. where the client needs this.

By default i think we should assume data and files are acl-public and can be read by anyone for *now* (i get for private datasets this *will* be needed - however, we are not *yet* supporting that use case).

**Comment by subhankarb** [comment]
As mentioned in https://github.com/frictionlessdata/dpr-api/issues/156 right now backend is sending only the object key but not the bucket name ..

**Comment by zelima** [comment]
@subhankarb @rufuspollock My guess here is for frontend js (graphs and tables). 
We need full path (link) to datapackage.json. Having only the s3 key would not be that useful, no?

**Comment by rufuspollock** [comment]
@subhankarb the backend should be sending to the frontend the full url path to the DataPackage - either the base directory or the datapackage.json (probably the latter).

**Comment by subhankarb** [comment]
@rufuspollock as discussed in https://github.com/frictionlessdata/dpr-api/issues/154 if we set up ```cloudfront``` we can get object just by calling 
- bits.{{domain}}.s3.amazonaws.com/{{objectkey}} [did this](bits.staging.datapackaged.com.s3.amazonaws.com)
- bits.{{domain}}/{{objectkey}} [if we set cert for this domain in cloudfont]

In that case what we are sending from backend is perfectly ok.

**Comment by rufuspollock** [comment]
@subhankarb great. So if this is under test the issue is closed right now. Well done!

Re cert for domain on cloudfront - can you mention this in #149

**Comment by subhankarb** [comment]
Fixed
