### ISSUE TITLE
[publish] Pre generated url is not working with md5 hash

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#160]
- [x] If we are adding md5 hash while generate the pre signed url for uploading resources, it is not working
- [x] Should return 400 if datapackage.json is in requested path

**Comment by pwalsh** [comment]
I've given links to working code for this stuff (hashes for presigned uploads), knowing that it is a pain to get right. Please go back to that and you could pretty much copy/paste the original work.

**Comment by subhankarb** [comment]
@pwalsh thanks ... we tried normal boto3 way. But it failing. Me and @Fak3 will go through that.

**Comment by subhankarb** [comment]
The pre-signed url is not working with md5 key.
Normally when put
```python
params = {'Bucket': bucket_name, 'Key': key}
url = s3_client.generate_presigned_url('put_object',
                                               Params=params,
                                               ExpiresIn=3600)
```
it works. 

But when put any other put_object parameter like ```ACL``` ```md5``` etc it throws
```
Error><Code>SignatureDoesNotMatch</Code><Message>
The request signature we calculated does not match the 
signature you provided. Check your key and signing method
```

If trying put header like ```Content-MD5``` in put request it throws ```Headers not signed```.
Tried almost all possible combinations. Have to raise an issue in ```boto3``` repo.

**Comment by subhankarb** [comment]
Pull request has been raised https://github.com/boto/boto3/issues/934
