### ISSUE TITLE
[doc] Authentication - auth0 and JWT

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#162]

**Comment by subhankarb** [comment]
Did not complete in 2nd Jan milestone moving to next milestone

**Comment by Fak3** [comment]
Authentication for the client side was documented https://github.com/frictionlessdata/dpm-py/issues/45

**Comment by Fak3** [comment]
https://github.com/frictionlessdata/dpr-docs/pull/7
