### ISSUE TITLE
[js] Convert all front-end code to react

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#173]
Right now we have part of the front-end code as react app. But we are not getting the benefit of react as for every request we are sending all front-end library every time. We have to refactor the whole front-end code in react to get full benefit of react app.
@rufuspollock and @anuveyatsu plz tell me your views.

**Comment by rufuspollock** [comment]
@subhankarb this is something we will think about but is a way off. I'd suggest we approach this incrementally. We also need to think about things like SEO set up.

**Comment by Fak3** [comment]
I think we are currently moving to the react in the dpr-js repo. I'd suggest to close this and instead report individual issues in case that some functionality or bug requires to refactor any existing js\templates\code.

**Comment by rufuspollock** [comment]
FIXED. See https://github.com/frictionlessdata/dpr-js/issues/67
