### ISSUE TITLE
Remove dataproxy api

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#174]
As we are using lambda as our server, there is some limitation of lambda.
- The response and request payload can not be more that 6MB

That is why we are fetching resources directly from front-end using s3 url. That is why our previously created apis:
- ```/api/dataproxy/{publisher}/{package}/r/{resource}.json```
- ```/api/dataproxy/{publisher}/{package}/r/{resource}.csv```
are not getting used. So it is safe to delete these two apis.

**Comment by rufuspollock** [comment]
Quick comments:

- For most front-end rendering or API work 6mb is fine so I am not worried about that limitation
  - right now if we try and render > 5mb CSV into front-end view page stuff will not work well
- In fact, 6Mb limit could be good.

So simple answer is: 6 MB limit is not an issue. Overall, I think we will want an API but we need to do more work on it and think how it will work.

**Comment by rufuspollock** [comment]
WONTFIX.
