### ISSUE TITLE
Make project modular 

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#175]
Right now the project is divided in two main part 
- mod_site
- mod_api
But as we are adding more and more api the ```mod_api``` module is getting really big.
So to make the project more modular we should split the ```mod_api``` in 3 parts
- mod_package
- mod_auth
- mod_search [as this will be one of the main functionality]

This is way code will more manageable

**Comment by pwalsh** [comment]
Why do you have the `mod_` name space? Seems unnecessary.

**Comment by subhankarb** [comment]
Ok i will do that.

**Comment by subhankarb** [comment]
Fixed. Right now there are three moduled
- package [holds all data package related apis]
- auth [holds all authentication and authorization apis]
- site [template rendering]

Future
- search [will holds all search apis]
