### ISSUE TITLE
List all Data Packages by Data Package Profile

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#181]
We need to list all data packages owned by the publisher.
```json
Api: /api/package/<name>?type=publisher
Request body:
{
   "page": 1,
   "page_size": 10
}

Response body
{
   "page": 1,
   "page_size": 10,
   "total_data": 55,
   "data": []
}
```

**Comment by subhankarb** [comment]
Closing will be handled by https://github.com/frictionlessdata/dpr-api/issues/200

**Comment by rufuspollock** [comment]
@subhankarb this is example where it will NOT be handled by #200. As per extensive discussions on calls we are NOT supporting search by Data Package profiles atm (we don't even have the information systematically).

**Comment by rufuspollock** [comment]
WONTFIX. We are not supporting search by data package profiles.
