### ISSUE TITLE
List all data packages

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#182]
We need apis for retrieve all data packages. Data packages are owned by user and publisher. So we need two separate Apis:
- [ ] List all data packages owned by user
- [ ] List all data packages owned by publisher
One common feature for both apis would be pagination.
```json
So commons request pattern would be:
Api: /api/package/<name>?type=user/publisher
Request body:
{
   "page": 1,
   "page_size": 10
}

Response body
{
   "page": 1,
   "page_size": 10,
   "total_data": 55
}
```

**Comment by rufuspollock** [comment]
Users don't own packages! Why not just implement a basic version of the search API here?

**Comment by rufuspollock** [comment]
Suggest we close as DUPLICATE in favour of search API epic.

**Comment by subhankarb** [comment]
Closing will be handled in https://github.com/frictionlessdata/dpr-api/issues/200

**Comment by rufuspollock** [comment]
@subhankarb when closing please mark as DUPLICATE and add duplicate label so it is clear what is happening.
