### ISSUE TITLE
Requirements Analysis for next iteration

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#185]
We have to analysis the dpr requirements for next iteration.

We are working on refining [user stories here][us]

[us]: https://docs.google.com/document/d/1O62Iim-iK1Xhsl19o5Ti9ERp1ZzQ3KxCt5OuUR3Q7hM/edit#

**Comment by subhankarb** [comment]
Did not complete in 2nd Jan milestone. Moving to 16th Jan milestone.

**Comment by rufuspollock** [comment]
So we spent 13h by Monday:

- All requirements reviewed and user stories generated for them
- User stories reviewed and refactored
- User stories prioritized
- Analysis started

Last 2d: 8h

- Further analysis of specific items
- Graphql investigation

**Comment by pwalsh** [comment]
@rufuspollock graphql is not a requirement.

**Comment by Fak3** [comment]
Tried to evaluate "import to Pandas" user story, encountered a bug: https://github.com/frictionlessdata/jsontableschema-py/issues/145

**Comment by rufuspollock** [comment]
@pwalsh got you that graphql is *not* a client requirement (and don't worry - we know that). But we do need to evaluate it as an implementation choice - we are doing a lot of frontend stuff and it might simplify that (and API work).

**Comment by subhankarb** [comment]
Fixed. The details are in  https://hackmd.io/IwdgnARhBmBsEFpoGMSwQFgMwFMsLACYATfYjCgVioA5oQBDIA==
