### ISSUE TITLE
When the token is expired, user is redirected to the non-existing page

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpr-api#191]
Steps to reproduce:
* login to the datapackage registry website (https://staging.datapackaged.com)
* wait for (an hour?) for token to expire
* refresh the home page

Result:
You are redirected to the url https://staging.datapackaged.com/staging/staging.datapackaged.com/logout, which does not exist.

**Comment by rufuspollock** [comment]
Another question for me: do you really get logged out after an hour? That is pretty annoying ...

**Comment by Fak3** [comment]
@rufuspollock Currently - yes. This time is hardcoded in the auth.models.JWT. We can increase it, but long-lived tokens are dangerous. I am unaware of the right solution to tighten the security right now.  Maybe we can also include users IP address in the token body and validate it on the server, so that leaked token can't be easily used...

**Comment by subhankarb** [comment]
Will be addressed in #231

**Comment by subhankarb** [comment]
FIXED.
Fixed with #235
