### ISSUE TITLE
Display the "loading" indicator while the table and graph is loading on the datapackage page

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpr-api#192]
Some datapackages are quite huge and it takes long time to render the table or graph on the datapackage page. Right now it is hard to tell if there was an error in the js script or it is still loading.

For example this one takes mor than 10 seconds for a table to show up: https://staging.datapackaged.com/core/finance-vix

**Comment by rufuspollock** [comment]
@Fak3 agree - this is a known issue that we can fix in the JS.

**Comment by rufuspollock** [comment]
DUPLICATE https://github.com/frictionlessdata/dpr-js/issues/118

Should not be a dpr-api issue as JS.
