### ISSUE TITLE
Dashboard page should have distinct url

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpr-api#197]
After the user logs in, he should be redirected to the /dashboard page

Extracted from https://github.com/frictionlessdata/dpr-api/issues/195

**Comment by rufuspollock** [comment]
@Fak3 why go to /dashboard rather than /? Choice of having base page as dashboard for logged in user was an intentional choice.

**Comment by Fak3** [comment]
As Paul mentioned, it is a confusing experience to have two distinct pages with the same url. If it is a root (home) page - registered user may think that it is how it looks like for everyone. Copying and sharing with expectation that other users will see some parts that only belong to his dashboard.

**Comment by rufuspollock** [comment]
WONTFIX.

@Fak3 I don't think this is confusing and it is a common pattern on many sites including e.g. github. If we really want documentation somewhere we can get a new url - i don't think sharing your dashboard url is that important.

Until we have more evidence this is confusing I'm going to close as wontfix.

**Comment by pwalsh** [comment]
I think the evidence for why it is confusing is in #195

**Comment by rufuspollock** [comment]
@pwalsh I read #195 and don't feel that was a key issue. Given that github and others have done this successfully for years I'd like to give this a little time to play out. If it really is a problem we should catch that pretty quickly with early users and can easily change it. Leaving as WONTFIX for now :wink:
