### ISSUE TITLE
Add helper methods for search data package

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#199]
We need [SQLAlchemy-Searchable](http://sqlalchemy-searchable.readthedocs.io/en/latest/index.html)

### What would query look like?

```python=
# added column name and readme to be searchable
# we can add weights to the search result just by adding weights.
# Here name will have heigher weight that readme.
search_vector = db.Column(TSVectorType('name', 'readme'),
        weights={'name': 'A', 'readme': 'B'})

# query for 'abc'
query = session.query(Package)
query = search(query, 'abc')

# query for 'abc' and publisher:core
query = session.query(Package).join(Publisher).filter(Publisher.name='core')
query = search(query, 'abc', sort=True)
```

### Simplest possible - no scoring)

No changes just use like query to search the pattern.

```sql=
-- for query abc 
SELECT * FROM package WHERE title LIKE '%abc%'
-- query for 'abc' and publisher:core 
SELECT * FROM package WHERE title LIKE '%abc%' AND Publisher.name = "xyz";
```
Right now going with second solution
Will implement advance search with https://github.com/frictionlessdata/dpr-api/issues/201

Tasks:
- [ ] Parse query string to searchable attributes
- [ ] Fetch data from database

**Comment by subhankarb** [comment]
INVALID.
The functionality is covered by #201 and #211

**Comment by rufuspollock** [comment]
@subhankarb please add the invalid label 😉
