### ISSUE TITLE
Implement Search using SQLAlchemy-Searchable

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#201]
For advance search we need SQLAlchemy-Searchable. This way we can easily implement ranking for different columns. Sql like query is only pattern matching query but with this we will have multiple words query

**Comment by rufuspollock** [comment]
INVALID.

IMO this is an issue that should be part of something else - the exact way we implement something can be part of issue description. E.g. this is part of implementing search by title or search in description ...
