### ISSUE TITLE
Implement publisher information api

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#202]
We need an api to fetch details of publisher information. 
Api:
```/api/profile/publisher/<name>```
Response:
```json
{
  "title": "", //like display name
  "joined":"",
  "writeup:"some details writeup about the publisher",
  "contact": {
   "email":"someone@some.com",
   "phone":"1234-1111" 
  },
  "country": "somewhere on earth" 
}
```

tasks:
- [ ] Add contact, writeup, country, title in publisher model
- [ ] Add controller for profile information

**Comment by Fak3** [comment]
fixed in #205

**Comment by rufuspollock** [comment]
@subhankarb why was this as `/api/profile/publisher`? That does not make a lot of sense to me - this should surely be at `/api/publisher/{name}` - can you explain why it is not.

Also I want to have at least a days notice on issues so they can be reviewed before they are implemented - this stuff should be in at the beginning of the sprint wherever possible.

**Comment by subhankarb** [comment]
@rufuspollock The thought behind the naming prefixed with /api/profile is that:
We need profile information for both user and publisher.
So both api would be:
- For publisher /api/profile/publisher/{name}
- For user /api/profile/user/{name}
[We are using Auth0 for using only verification. Every time user logged in or signup the db gets synced. ]
