### ISSUE TITLE
Implement data package information api 

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#203]
Right now we return template for data package details page. This include package url, readme and other details.
We need an api to get package information to implement datapackage view page in react.
Api:
GET /api/package/<publisher>/<package>/info
response:
```json

{
"url": "",
"readme:""
}
```

**Comment by Fak3** [comment]
Why we need it? Frontend could derive any backend url itself. And pull the readme from bitstore.

**Comment by rufuspollock** [comment]
I agree with @Fak3 and I also thought the package API returned the full descriptor for the datapackage?

@subhankarb please provide a lot more information about the current situation and the proposed change before we implement this.

**Comment by subhankarb** [comment]
Closing we already have that api as  /api/package/<publisher>/<package>
