### ISSUE TITLE
Local tests failing with psycopg2.OperationalError: "dpr_db_test" does not exist

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpr-api#208]
Following README instructions, tests are failing:
```
$ FLASK_CONFIGURATION=test pytest
...
OperationalError: (psycopg2.OperationalError) FATAL:  database "dpr_db_test" does not exist
```

README should have full info on how to launch tests. This includes tests database and user setup.
Related: #103

**Comment by subhankarb** [comment]
@Fak3 / @rufuspollock could not reproduce the error. In my work station it is working.

**Comment by rufuspollock** [comment]
INVALID. @Fak3 please reopen if you think this is actually still a problem.
