### ISSUE TITLE
Analysis for 13 Feb 2017 sprint

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#220]
- [x] Check we have user stories for all sprint items - create, improve and comment
  - [x] Search - already done!
  - [x] Data Package View - what is done? What are acceptance criteria @rufuspollock
  - [x] dpmpy datavalidate @Fak3 
  - [x] dpmpy undelete @Fak3 
  - [x] dpmpy tag @Fak3 
  - [ ] dpmpy install @rufuspollock
  - [x] UX / Site looks nice @rufuspollock
- [x] Do analysis for these user stories (output: analysis suitable for becoming an issue plus estimate)
   - [x] Search analysis: do a new analysis just focused on what we need to do this sprint.
     - How much work is simple title versus "proper search" over README and title (and maybe other fields)
  - [x] Revert to MPA (from SPA) #222 
  - [x] dpmpy datavalidate
  - [x] dpmpy undelete
  - [x] dpmpy tag
- [ ] Create github issues

**Comment by rufuspollock** [comment]
FIXED.
