### ISSUE TITLE
Migrate from Bootstrap3 to Bootstrap4

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#224]
We use bootstrap 3 for styling. Bootstrap 4 come with lot of new improvements. So we want to migrate to bootstrap 4.

## Tasks:

- [x] Change bootstrap components for these html pages:
  - [x] Base.html
  - [x] Index.html
  - [x] Dashboard.html

**Comment by pwalsh** [comment]
it is still in alpha.

**Comment by subhankarb** [comment]
@pwalsh AFAIK alpha-6 is the last alpha release. They are releasing beta next month. They added flex support in BS4 and a lot more improvements.
@rufuspollock what is your review about this issue?

**Comment by rufuspollock** [comment]
@pwalsh I get this is alpha but we evaluated the changes and they are fairly minor (not like 2->3) and we think this is a small bit of useful future-proofing.
