### ISSUE TITLE
Blank page header when window width is less than ~1180px

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpr-api#243]
In Firefox and chrome i see blank page header on any page if the window width is less than some value:
http://i.imgur.com/rtI03Rm.png

If the window is wide enough, everything is ok:
http://i.imgur.com/dJGbhc5.png

**Comment by zelima** [comment]
FIXED. Out of date - can not reproduce this any more. Feel free to reopen if this still remains as issue
