### ISSUE TITLE
Compare OS platform and this platform and identify reuse possibilities

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#246]
* [x] Review gobble vs dpmpy
  * [x] How would we merge these
  * [x] What is different in terms of expected API
  * [x] What should we change in dpr-api and what in conductor to converge these together
* [x] Review os-conductor vs dpr-api
  * [ ] What are the key components - what are similar and what are different

**Comment by Fak3** [comment]
## Suggestions to converge restapi urls
### Current situation
#### Conductor
* Request presigned url - `POST /datastore/authorize` for all resources at once  (+datapackage.json)
  * request should have json with perpared list of resource paths, md5 hashes, filesize
  * response will be a list of filepaths with corresponding presigned urls (plus some other stuff of unknown use)
* Finalize upload - `POST /package/upload` 
  * request should have `datapackage.json` content inside
  * response will have json with 'status': 'queued' on success.
#### DPR
* Request presigned url - `POST /api/auth/bitstore_upload` many times for each resource  (+datapackage.json)
  * request should have publisher_name, package_name, filepath, md5hash for one file
  * response will have presigned url, and its query params
* Finalize upload - `POST /api/package/{publisher}/{package}/finalize`
  * request: no data
  * response: status 200 on success
### Proposal 
* Request presigned url - `POST /api/package/{publisher}/{package}/upload_urls` for all resources at once (+datapackage.json)
  * request should have list of {filepath, md5hash, filesize} for each file
  * response will be a list of filepaths with corresponding presigned urls
* Finalize upload - `POST /api/package/{publisher}/{package}/upload_finalize`
  * request: no data
  * response: status 200 on success

**Comment by rufuspollock** [comment]
FIXEd. We did analysis and created https://github.com/frictionlessdata/dpr-api/issues/249
