### ISSUE TITLE
Accept metadata in the finalize api request

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpr-api#247]
To merge with openspending we can switch to the same upload api flow. This means:
* remove `PUT /api/<publisher>/<package>` api 
* move its logic into `POST /<publisher>/<package>/finalize` api
   * accept metadata (datapackage.json) in the request content json body

**Comment by rufuspollock** [comment]
@Fak3 i don't think you move the metadata into finalize. instead datapackage.json is uploaded to BitStore and then imported like we import the README. Can you also open the epic for this in dpr-api ...

**Comment by Fak3** [comment]
WONTFIX. We can keep the finalize endpoint as we have now.
