### ISSUE TITLE
Create /api/bitstore/authorize_upload endpoint

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpr-api#248]
The api should be mostly the same as in os-conductor: see docs at http://docs.openspending.org/en/latest/developers/conductor/#get-authorized-upload-urls

The enpoint should accept json object in request body with the following format:
```
{
    "metadata": {
        "owner": "<publisher-name>",
        "name": "<data-package-name>"
    },
    "filedata": {
        "<relative-path-to-file-in-package-1>": {
            "length": 1234, #length in bytes of data
            "md5": "<md5-hash-of-the-data>",
            "type": "<content-type-of-the-data>",
            "name": "<file-name>"
        },
        "<relative-path-to-file-in-package-2>": {
            "length": 4321,
            "md5": "<md5-hash-of-the-data>",
            "type": "<content-type-of-the-data>",
            "name": "<file-name>"
        }
        ...
    }
}
```

The endpoint should behave mostly the same as os-conductor: see code [here](https://github.com/openspending/os-conductor/blob/master/conductor/blueprints/datastore/controllers.py#L32).
I.e. it should take each file from the `request['filedata']`, create s3 presigned url for that file with base s3 key `{prefix}/{publisher}/{package}/_v/lastest/`(as we currently have - no change) and construct json response:
```
{
'filedata': {
     "<relative-path-to-file-in-package-1>": {
                'upload_url': upload_url1,
                'upload_query': upload_query1},
     "<relative-path-to-file-in-package-2>": {
                'upload_url': upload_url2,
                'upload_query': upload_query2},
    ...
}}
```

Authentication: the same as we currently have - no change for now. (use jwt in "Authentication" header)

**Comment by subhankarb** [comment]
FIXED.
Done with the pull request #253
