### ISSUE TITLE
Use 'Auth-Token' instead of 'Authentication' header

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpr-api#250]
To merge with os-conductor, we should adopt the same auth header 'Auth-Token'.
Also the header content should not start with 'bearer', as it does now. (use plain jwt)

**Comment by subhankarb** [comment]
@Fak3 It seems that `jwt` is passing in post body. As jwt is retrieved with 
```python
jwt = request.values.get('jwt')
```

**Comment by Fak3** [comment]
@subhankarb their auth is inconsistent between blueprints. I the datastore they use the headers.

**Comment by subhankarb** [comment]
FIXED.
Done with the pull request #253
