### ISSUE TITLE
Openspending-compatible upload finalization api.

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpr-api#251]
To merge with os-conductor we should try to be compatible in the finalize upload API.

* Change url to `/api/package/upload`

* Request body should be json object in the format: `{'datapackage': 'url'}`
  * 'datapackage' should be url of the `datapackage.json` that was previously uploaded by the client on the BitStore
     * That url should be used in the controller code to fetch metadata and as base to fetch README contents.
* Currently we return `'status': 'OK'`, on success, but we should return `'status': 'queued'` instead.
(*In the future we will have async job starting on the request. Right now it is not a priority. So no change for now*)

**Comment by Fak3** [comment]
Hm... I actually think that the 'status' should be better renamed to 'job_status', to clearly separate request status (as in http terms) and job status.

**Comment by subhankarb** [comment]
FIXED.
Done with the pull request https://github.com/frictionlessdata/dpr-api/pull/253
