### ISSUE TITLE
[js] DATA_PACKAGE_URL is not passed from dpr-api

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#254]
In new implementation of dpr-js in `index.jsx` the container `DataPackageView` needs two parameters 
- DATA_PACKAGE
- DATA_PACKAGE_URL

In the previous implementation this container needed `publisher` and `package` as parameters. 
So we need to pass these two variables form API `GET /<publisher>/<package>`
and set these two parameters in `dataset.html`

## Tasks

- [x] Set  `DATA_PACKAGE` and `DATA_PACKAGE_URL` in `_snippets.html`
- [x] Update API `GET /<publisher>/<package>` parameters.

**Comment by rufuspollock** [comment]
I'll fix this now. Forgot to make this change when i updated the submodule.

**Comment by subhankarb** [comment]
@rufuspollock i was doing this. Already finished. Should i raise pull?

**Comment by subhankarb** [comment]
FIXED.
Addressed in this commit: https://github.com/frictionlessdata/dpr-api/commit/4e47b26e8f2a8889dbfb689be38dd456c80cfe6e
