### ISSUE TITLE
Issues with password change

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/dpr-api#257]
- Password change occurs on a completely unrelated domain. The successful action leaves me on that domain, and a confused user.
- Because of above - it breaks the way password managers work - I let my password manager generate a random password, and it does so on the new domain, and therefore does not associate my password with the actual domain I want to log in to (nor with an email or username, as that is not part of the reset password form). As a heavy random password user, this never happens.

<img width="1280" alt="screenshot 2017-02-28 13 45 30" src="https://cloud.githubusercontent.com/assets/791678/23404187/52f04dea-fdbc-11e6-8e0b-ef8a44a490e4.png">

**Comment by rufuspollock** [comment]
Documenting the old process:

  - The redirection will go to auth0 side as auth0 manages the password change.
  - right now the process is
  
    ```mermaid
    graph TD
    A("Don't remember your password?") --> B
    B("Enter email ") --> C
    C("Auth0 send email with reset password link like this") --atomatichq.eu.auth0.com/lo/reset?ticket=*--> D
    D("Enter new password") --Success--> E
    E("Login in 'datapackaged.com'") --> F("Success")
    ```

**Comment by rufuspollock** [comment]
INVALID. We've switched off Auth0 and won't have password login - see #268
