### ISSUE TITLE
App randomly throws error messages

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/dpr-api#258]
<img width="1280" alt="screenshot 2017-02-28 13 48 44" src="https://cloud.githubusercontent.com/assets/791678/23404256/ae9b980c-fdbc-11e6-9cf5-44e051bfed37.png">

**Comment by pwalsh** [comment]
Actually - maybe not random - this is **all** I get after I did the reset password....

**Comment by rufuspollock** [comment]
@pwalsh we've encountered this randomly as well and spent time looking at i without finding a pattern or source. 

@subhankarb any comments.

**Comment by subhankarb** [comment]
I saw this issue sometimes but it is rare.
- Had to redeploy every time. It may be a bug in zappa.
- I reported this at https://github.com/Miserlou/Zappa/issues/351

**Comment by flux627** [comment]
Try updating to the latest Zappa version, there was a regression from 6 days ago that was just fixed.

**Comment by rufuspollock** [comment]
FIXED / INVALID. No longer an issue since we moved off zappa and lambda.
