### ISSUE TITLE
[ux]  Publisher avatar is not right size

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#266]
The avatar icon of publisher is not right size. It appears larger.

Below is the snapshot of the issue
<img width="698" alt="screen shot 2017-03-06 at 12 21 16 pm" src="https://cloud.githubusercontent.com/assets/2178361/23599494/7d311ada-0267-11e7-8e9a-4a6d34c9cfcf.png">

**Comment by rufuspollock** [comment]
Should be part of bigger improvement to publisher page as part of new theme epic #245

**Comment by anuveyatsu** [comment]
This is because we've been building on Bootstrap v4 and then changed to v3.
Just need to change class name for `img` element to `img-responsive`.
