### ISSUE TITLE
Description excerpt at top of view page has unrendered markdown

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#270]
Short description at top of page includes non-parsed markdown - see e.g. https://staging.datapackaged.com/core/gold-prices which has

> "Monthly gold prices since 1950 in USD (London market). Data is sourced from the Bundesbank. ## Data * [Bundesbank statistic..."

Solution (as in old site): parse markdown to html, then de-htmlify and then do selection of first XX characters (i think we actual had a function for this in jinja / nunjucks - check old code)

## Tasks

* [ ] Failing test (? - could leave out as so trivial - but tests are good!)
* [x] Fix it

## Acceptance Criteria

* [x] Gold prices README excerpt looks nice (no markdown)

**Comment by subhankarb** [comment]
FIXED.
Added markdown format for README. Did not add any test as could not found any obvious way to test it. 
One way is to push manually a README file with heading with 2 `#` then check it rendered as `h2`. But looked little over kill for this small issue.

**Comment by subhankarb** [comment]
FIXED.
