### ISSUE TITLE
Remove ambiguous db call for user email

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#310]
Change sql-alchemy call from `.first()` to `.one()`

## Context

We are getting user email while generating jwt token. While calling db we are using `.first()` method.
Previously we were using auth0. There email id was not unique. We were relying on auth0 user id. But now we are using github for authentication. We changed the DB model to 
`email = db.Column(db.TEXT, unique=True, index=True)`
So email supposed to be unique.

## tasks

- [x] Change [sql-alchemy](https://github.com/frictionlessdata/dpr-api/blob/master/app/auth/controllers.py#L137) method from `.first()` to `.one()`
- [x] Change [sql-alchemy](https://github.com/frictionlessdata/dpr-api/blob/master/app/auth/controllers.py#L128) method from `.first()` to `.one()`

**Comment by zelima** [comment]
FIXED
