### ISSUE TITLE
Create example data packages

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/dpr-api#319]
*Excellent: elegant, easy to understand, good demonstrations.*

### Acceptance Criteria

* Basic range of examples
  * Data types:
    * Tabular
    * Geo - map
    * Tabular + Geo
    * Mixed (? - could be part of a vega example)
  * Views
    * Simple view - could combine with simple data
    * Multiple views
    * Vega examples (several)
* Each data package should function as interesting and useful in itself and as a tutorial (if good enough tutorial could be implicit rather than explicit)
  * Embed datpackage.json - can we support this in markdown
  * README should be written as proper data packages "Yields of Barley for xxx. This is an example data package that demonstrates using ...".
  * Good title
  * ...
* Locate under `examples` publisher
  * But that may be a problem as we have no way to create publishers atm => but maybe good to create this.

### Actions

- Choose at least 5 datasets to have as an examples:
    - [x] Tabular + Simple view: https://staging.datapackaged.com/anuveyatsu/finance-vix
    - [x] Geo - map: https://staging.datapackaged.com/anuveyatsu/ex-geojson and github https://github.com/anuveyatsu/DEMO-datapackage-geo-map
    - [x] Tabular + Geo: we could use followings:
        - https://github.com/frictionlessdata/example-data-packages/tree/master/gross-domestic-product-2014
        - https://github.com/frictionlessdata/example-data-packages/tree/master/geo-countries
    - [x] Multiple views: TODO - use one simple view and one vega view
    - [x] Vega examples:
        - https://staging.datapackaged.com/anuveyatsu/barley
        - https://staging.datapackaged.com/anuveyatsu/lifelines
        - https://staging.datapackaged.com/anuveyatsu/us-airports-connections

**Comment by zelima** [comment]
FIXED

**Comment by rufuspollock** [comment]
@zelima @anuveyatsu i'm going to leave this FIXED on this occasion but it was a close one :wink:. @zelima please open a follow up issue to document all the outstanding items.

Key learnings:

- Do one example package first and really polish until it is correct then do the others
- Use this as a dogfooding exercise and it is worth taking the time to make core fixes to make your life easier e.g. the {{datapackage}} markdown

**Comment by zelima** [comment]
Follow up here https://github.com/frictionlessdata/dpr-api/issues/333
