### ISSUE TITLE
Fix the invalid year/date for some of datapackages 

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/dpr-api#321]
Some of the datapackages Like [Purchasing power parity (PPP)](http://staging.datapackaged.com/core/ppp) fail to load data

Error message: `Wrong type for header: Year and value: ////`

## Suggested solution

One suggested solution would be to change type for `Year` column to `number`  - this worked for https://staging.datapackaged.com/core/ppp

**Comment by rufuspollock** [comment]
@zelima i think we want to think more about the exact solution. Switching to number is not really correct IMO. See discussion in https://github.com/frictionlessdata/dpr-js/issues/121

Options:

* Change type to new `year` type (in upcoming release - but not supported in current js lib!)
* Change to type `date` with format filed as per https://github.com/frictionlessdata/dpr-js/issues/121
* Turn off data validation in the JS lib (is this possible?)
* ...?

**Comment by zelima** [comment]
This now becomes DUPLICATE of #331
