### ISSUE TITLE
Publisher page is loading for not existing users

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-api#325]
E.g., when I go to random user's page, which very likely does NOT exist, it still loads a publisher page:
http://staging.datapackaged.com/lkndslfsdflksfnlkasdknlasd

## Acceptance criteria 

- [x] Non existing users page (or any other) should result with `404 page not found`

## Tasks 

- [x] write tests
- [x] refactor code

**Comment by zelima** [comment]
FIXED
