### ISSUE TITLE
Get all the Emails for users from github API

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/dpr-api#339]
We are still not getting a guaranteed user email -- only getting an email if it is public.
Results of that:

- gravatars are broken (we have generic gravatar) 
- we cannot email them if needed (almost certainly will need)

# analyzes 

Reason and solution for this is in http://stackoverflow.com/questions/35373995/github-user-email-is-null-despite-useremail-scope

To get private emails we need to call: `GET https://api.github.com/user/emails`

# acceptance criteria

- [x] all of our users have guaranteed emails (even if email is not public)
- [x] emails are ones that are have "primary" flaf

**Comment by rufuspollock** [comment]
@zelima - great to see this done. Couple of minor process improvements:

* we need a FIXED comment as well as closing in a commit (see our process guide)
* Also, it would be good to have had clearer analysis including acceptance criteria and tasks

**Comment by zelima** [comment]
We do note have test for case where there is no public email and we have to perform a second request, because was not able to work out how to mock two different responses for `flask_oauthlib.OAuthRemoteApp.get` - Need help here

**Comment by rufuspollock** [comment]
@zelima you need to explain your problem in more detail. Link the current test and explain what you want to do ...

**Comment by zelima** [comment]
@rufuspollock I have a code snippet https://github.com/frictionlessdata/dpr-api/blob/master/app/auth/controllers.py#L56
```
user_info = github.get('user')
user_info = user_info.data
# in case user Email is not public
if not user_info.get('email'):
    emails = github.get('user/emails').data
        for email in emails:
            user_info['email'] = email.get('email')
```
This makes to different API calls in different cases - `https://api.github.com/user` and if not found public Email: `https://api.github.com/user/emails`
All this is done by `get()` method of `0auth.remote_app`

In the mocks we are trying to stub the return value of `get()` method Eg: 
```
@patch('flask_oauthlib.client.OAuthRemoteApp.get')
def test_return_200_if_all_right(self, get_user):
        get_user.return_value = OAuthResponse(resp=None,
                                              content=json.dumps(dict()),
                                              content_type='application/json')
```
This works fine for first API call `users/` but how to mock second API call? 
Actually how to mock both of them? cause we need to do 1st call -> check if has Email and when it does not -> do another

**Comment by rufuspollock** [comment]
@zelima first, great write up of the problem.

Second, we need to think conceptionally. What do you want to mock and how? Specifically, here you could mock:

* Stub out `github.get` in the library
* Mock out http requests like nock does for node - https://github.com/node-nock/nock (this is what we use in dpr-js). Basically, here we mock out underlying http calls.
  * question: does something like nock exist for python? Probably yes: e.g. https://www.google.fr/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=mock+http+python

If you are going with the first approach then your mocks are going to have to be smart enough to return different things for different requests.

**Comment by zelima** [comment]
FIXED we get Emails in any case - private or not. Both options are under tests
