### ISSUE TITLE
Render README markdown in safe mode

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-api#347]
Render README markdown in safe mode (disallow <script>)

> User story:
> As a site developer I do **not** want people to inject scripts along with README so that our system is secure and does not compromise those who visit our site.

## Analysis

Using HTML tags along with Markdown is convenient for wide range of users - e.g. some may not know Markdown syntax. However, we cannot allow all HTML tags to be used as that would make our site insecure (e.g. XSS). We need to have a list of HTML tags, attributes etc., that are considered safe. We could use GitHub's whitelist of HTML tags from their sanitization filter:
https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/sanitization_filter.rb

> Note: we could use Markdown library's `safe_mode` however that removes all HTML tags plus it is now deprecated for security reasons and they recommend `bleach` library. https://pythonhosted.org/Markdown/reference.html#safe_mode

For sanitization of user inputs (README) we can implement `bleach` library - https://pypi.python.org/pypi/bleach :

```python
# in controller
from markdown import markdown
import bleach

# setup what is allowed
bleach.sanitizer.ALLOWED_TAGS = ['h1', 'h2', ...]
bleach.sanitizer.ALLOWED_ATTRIBUTES = [...]
bleach.sanitizer.ALLOWED_PROTOCOLS = [...]

# sanitize README text
sanitizedReadme = bleach.clean(README)

# markdownify sanitized text
README = markdown(sanitizedReadme)
```

```html
<!-- template -->
<div class="readme">
  {{ dataset.readme | safe }}
</div>
```

## Tasks

- [ ] refactor `app/controller.py`
- [ ] hand test `<script>` tags are being escaped like in GitHub README (e.g. [github readme][github-readme])

[github-readme]: https://github.com/datapackage-examples/mixed-views/blob/master/README.md

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-api/commit/3be8ddcefdf384b928714e3e6a9a3b834c7464cb

**Comment by anuveyatsu** [comment]
We need to escape **only** `<script>` tags, not all HTML tags.

**Comment by rufuspollock** [comment]
@anuveyatsu looks excellent. Added a small comment indicating why we are thinking of using bleach and not `safe_mode`.

In terms of implementation:

* This markdown stuff should be in a helpers section of the site - and used from controller (should definite not be in the controller)
* The preparation of a data package for rendering should be done in a logic section of the app (and that logic method uses the markdown helpers) --  this part of a larger refactoring though probably
* After we've done this change we can probably throw out flask-markdown as we won't be doing any markdown processing in templates (that is probably good practice in fact!)

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-api/pull/351
