### ISSUE TITLE
Identify use cases we have where DP Pipelines are relevant

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#357]
To have a clear Idea what are DataHub needs that could benefit from DP Pipelines  list of use cases where DPP are relevant

## Acceptance Criteria

* [x] we have 3-4 clear, easily understandable use cases, listed out in "analysis" section

## Tasks

* [x] Understand our needs and understand how data package pipelines relate to those needs
  - Review meeting docs
  - Review meeting recording

#### Use case N1 - Scrape data from internet and update automatically 

As a Publisher I have found some useful data somewhere in the internet and want to get (scrape) it and publish the data on our platform. I want to scrape the data from website, add metadata,  validate data and publish on datahub  and do this every day in auto mode without running script locally every day.

- Using the DPP features(built in tools) like `add_metadata`, `scrape`, celery and data validation it would be easy to do

#### Use case N2 - Join resources together

As a Publisher I have several resources (csv files) that have different fields, but they also have common fields. I want to concatenate those common fields and get a new resource after I would add metadata and publish it so that other could see with nice graphs and charts

- use dpp `join` and `add_metadata` tools

#### Use case N3 - transform data

A a publisher I want to make some changes to data Eg remove column / change order of columns / change type of fields and have automatically updated it on DataHub. 

- The DPP Standard Processor Library could be highly useful.

#### Use case N4 - Do custom analysis / data transforms

As a user I wants to do my own analysis according to data with small script I wrote and add calculated results as a new column in existing csv file and have my results published on datahub 

- DPP allows to define custom functions as a jobs to use plus builtin `concatenate` tool that will help with updating existing file with new field.

**Comment by zelima** [comment]
FIXED. See analysis section for use cases
