### ISSUE TITLE
[publish] Create new data package from metadata

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/dpr-api#4]
`POST /api/package/{publisher}/{package}`

Create / update data package with new metadata

Parameters:
- Data Package metadata (`datapackage.json`) 
- Auth info

Returns:

```
SUCCESS

{
   "message": "Data Package created"
   "url": "url to data package" [really needed as user get this through api]???
}

FAILURE: (http code ...)

{
  "message": "Invalid data package"
}, 400
{
  "message": "Not authorized to publish"
}, 401
{
  "message": "Failed to store data package"
}, 500
```

Tasks
- [x] Test for all of this
- [x] Auth: check token
- [x] Validate this data package and fail if wrong
  - [x] Validate the user id (from token) and user name to validate user
- [x] Store data into S3

**Comment by rgrp** [comment]
@subhankarb can you fill in sections re parameters and success / failure results.

**Comment by subhankarb** [comment]
@rgrp  ```{"url": "url to data package"} ``` [really needed as user get this through api]???

**Comment by rgrp** [comment]
@subhankarb hmmm i guess i was thinking the actual API should be:

```
POST /api/package
```

Which would be more classic style - but leave us to decode the publisher and package name from the posted JSON. So I guess you are right for now and that means we should correct to have empty return info.

**Comment by subhankarb** [comment]
The swagger spec for the publish call 
Partly addressed by https://github.com/frictionlessdata/dpr-api/pull/23
and initially implemented by https://github.com/frictionlessdata/dpr-api/commit/aa4cc7815b7d090b0a8d28d7a080a1ce5a694b43
and other part implemented before move to github
```
{
	"/api/package/{publisher}/{package}": {
		"put": {
			"description": "This API is responsible for pushing  datapackage.json to S3.",
			"parameters": [{
				"description": "publisher name",
				"in": "path",
				"name": "publisher",
				"required": true,
				"type": "string"
			}, {
				"description": "package name",
				"in": "path",
				"name": "package",
				"required": true,
				"type": "string"
			}],
			"responses": {
				"200": {
					"description": "Success Message",
					"schema": {
						"$ref": "#/definitions/api_save_metadata_put_put_package_success"
					}
				},
				"400": {
					"description": "JWT is invalid or req body is not valid"
				},
				"401": {
					"description": "Invalid Header for JWT"
				},
				"403": {
					"description": "User name and publisher not matched"
				},
				"404": {
					"description": "User not found"
				},
				"500": {
					"description": "Internal Server Error"
				}
			},
			"summary": "DPR metadata put operation."
		}
	}
}
```

**Comment by rgrp** [comment]
@subhankarb do we allow both put and POST?

**Comment by subhankarb** [comment]
@rgrp only PUT

**Comment by rgrp** [comment]
@subhankarb can we change to allow both POST and PUT. After all i imagine we will use the same API for updates as well as create ...
