### ISSUE TITLE
Swagger API docs working on deployed site

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#45]
At the moment there is an issue due to way the flask zappa deploy works ...

**Comment by rufuspollock** [comment]
Won't happen this sprint.

**Comment by subhankarb** [comment]
Fixed when deployed with fixed domain name. As previously it was deployed with zappa stage endpoint.
Example:
With zappa the endpoint was ```{{host}}/stage/apidocs/index.html```
Internally it was redirect to ```{{host}}/spec``` for spec json. but that was wrong path.
After deployed with fixed domain ```staging.datapackaged.com``` the api docs is redirecting to right endpoint.
