### ISSUE TITLE
Data Proxy for CSV and JSON versions of CSV data

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/dpr-api#46]
API is at:

```
/api/dataproxy/{publisher}/{package}/r/{resource-index-or-name}.csv
/api/dataproxy/{publisher}/{package}/r/{resource-index-or-name}.json
```

* [x] CSV option
* [x] JSON option
* [x] Streaming support
* [x] Tests

<del>Unfortunately python has no native way to stream afaik so just dump the whole file back. Worry about very large files later ...</del>

**Comment by pwalsh** [comment]
python can definitely stream a response even with plain ol' Python 2: http://flask.pocoo.org/docs/0.11/patterns/streaming/

**Comment by rgrp** [comment]
@pwalsh my ignorance ;-) @subhankarb + @zelima can we use the streaming option if it is easy to do.

**Comment by zelima** [comment]
Endpoints should be changed
```
/api/dataproxy/{publisher}/{package}/{resource-index-or-name}.csv -> /api/dataproxy/{publisher}/{package}/r/{resource-index-or-name}.csv 
/api/dataproxy/{publisher}/{package}/{resource-index-or-name}.json -> /api/dataproxy/{publisher}/{package}/r/{resource-index-or-name}.json
```
Currently format of returned data by endpoints are 
- `{"data": "header1,header2\value1,value2"} ` fro csv
- currently not working for json

Should be changed to:
- `header1,header2\value1,value2` for csv
- `[{"header1":"value1", "header2":"value2"}, {"header1":"value3", "header2":"value4"}, etc]`

**Comment by rgrp** [comment]
@zelima who owns this issue? Are you doing this or @subhankarb? Please can we assign and complete this item and close.

**Comment by zelima** [comment]
CSV needs to be converted into json. Reopening
