### ISSUE TITLE
[super] Data Package view page

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/dpr-api#47]
* [x] Working with fixture data
* [x] Working with metadata (pulled via API) - #60
* [x] Tables and graphs working (needs data proxy implemented #46)
  * Need to change API locations for new API ... 
* [x] Functional tests for page

**Comment by zelima** [comment]
Fixed: this should be working

**Comment by rgrp** [comment]
Various things to do and missing tests so reopening.

**Comment by zelima** [comment]
Closing as all of them should be working

**Comment by rgrp** [comment]
Reopening as:

- README excerpt is not showing up at top
- Issues with loading some libraries over https which means table breaks

**Comment by zelima** [comment]
One option would be to include http://okfnlabs.org/csv.js/csv.js into the vendor dir

**Comment by rgrp** [comment]
FIXED. Outstanding issue re csv.js is #92
