### ISSUE TITLE
[publish] Authorize file upload to BitStore

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#5]
`POST /api/auth/bitstore_upload`

POST file info and receive signed upload auth to S3
- [x] Parameters: package info: `publisher`, `package`
- [x] File parameters:
    - [x] (relative)  path, 
    - [x] md5 hash ...
- [x] ensure path is *not* `datapackage.json` (we do not want users uploading their datapackage.json directly as we want to validate it)
- [x] Returns: s3 signature for uploading directly

**Comment by Fak3** [comment]
@rgrp What do we need md5 hash for? If it is to generate unique s3 key for a resource - can the server itself just hash the publisher_name+datapackage_name+resource_path?

**Comment by rgrp** [comment]
@Fak3 IIRC the S3 request signing requires the md5 stuff as part of it. We should maybe check the boto docs. In general, including the md5 hash is good practice to ensure that a user did not upload something other than what was authorized for upload. Here that might not be so relevant since we assume user will have authorization to upload anything they like. However, it would still be good practice.

**Comment by pwalsh** [comment]
It is part of the authorisation of the S3 service itself - you give a user a temp url for upload, and that URL knows the hash of the file to be uploaded, and thereby ensures that what is uploaded is actually what was authorised.

That example from the old os-cli code that @rgrp shared somewhere here or in Gitter should show the whole flow if you set a trace and step through with `ipdb` or something. 

We also have more modular versions of this flow in Open Spending if that helps, where we have, for example, a distinct web service that handles the creation of the upload urls etc. 

You can find the blueprint for this in the `os-conductor` app, here: https://github.com/openspending/os-conductor/tree/master/conductor/blueprints/datastore

**Comment by Fak3** [comment]
The hash is optional, not a requirement. We can generate upload url without it:
```
params = {'Bucket': 'mybucket', 'Key': 'test/publisher/package/v1/res1.csv'}
url = s3.generate_presigned_url('put_object', Params=params, ExpiresIn=3600)
```
So do we need it an go the same way as os-conductor? I thought we can relieve

**Comment by pwalsh** [comment]
@Fak3 up to @rgrp but if you don't do this, it means someone can do:

1. Give me permission to upload `good.csv`
2. Now I'll upload `bad.js`

Now obviously a whole bunch of other things should happen with uploading - checking the path of files (they are in the datapackage for example), and maybe also checking format and size (do we accept 4GB CSV files?, do we accept `.js` extensions?), but a basic transaction that says "I'll let you upload exactly what you asked permission to upload, no more, no less", is a pretty good starting point for security and *control*.

**Comment by Fak3** [comment]
@pwalsh the hash won't prevent user from uploading bad.js if he gave us hash of bad.js in the first place. He gives us hash of something, and uploads it, and we have no idea of what that is until he finishes the upload. It seems to me that the whole point of "what you asked permission to upload" exists when we can make some checks of the thing being uploaded beforehand. 

The size limit looks useful. But I am not yet sure if and how the amazon will limit it during upload (to prevent traffic abuse it should break the stream after the exact size receieved)

On the validation - after upload, the server will have to validate resources to conform to the schema, that was given in the datapackage.js. There is a comment about it in the Technical Architecture doc.

**Comment by pwalsh** [comment]
ok, last comment:

1. I know it won't prevent uploading bad.js if that was the original file requested for upload
2. You need to do checks on client and server anyway, this is just one of many such checks
3. hashing also helps ensure data integrity
4. if you do *validation* client side, and then hash your payloads, then you don't have to do it server side - huge win for compute resource management.

**Comment by Fak3** [comment]
Well, the whole trust and abuse topic is not documented or even thought out atm.

**Comment by Fak3** [comment]
When client uploads resource file to the url returned, it will overwrite datapackage.json created on the first step (metadata upload). This does not makes sense. Istead the server should create url pointing to some temporary key in the bucket and return it. After the client uploads all resource files, it will send finalization request. On the finalization request server should validate all the data uploaded by the client and after that move all the resources from temporary keys to the relevant persistent keys on the bitstore. Then move datapackage.json to the persistent place on the bitstore and maybe somehow flag the ingestor that the package can be grabbed from bitstore to the structured database.

**Comment by rgrp** [comment]
@Fak3 as per @pwalsh comments the point of hashing is more about man in the middle attacks and avoiding some issue where data that is supposed to be sent is not sent. It is not about preventing a malicious adversary who is authorized to upload uploading bad stuff.

Summary: please include the hash in the signing of the upload as it is trivial to do and has value.

**Comment by rgrp** [comment]
@subhankarb what's the status here? Can we check off the items?

**Comment by subhankarb** [comment]
Fixed all tasks
