### ISSUE TITLE
Review tests and code quality

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/dpr-api#61]
* [x] Check conformance with https://github.com/okfn/coding-standards#style-and-linting
* [x] Are tests well laid out and understandable
* [x] Do we have *reasonable* (not nec perfect) test coverage?

**Comment by zelima** [comment]
@rgrp @subhankarb I'll update this as something new comes up
After reviewing test `mod_api/test_models.py` test not cover:
- relations between tables are set as needed.
- user info is not overwritten if user with same "user name" tries to sign up (does auth0 takes care of this?)

**Comment by zelima** [comment]
With latest merge coverage will be increased till 91%. + Test for homepage are coming up, this will probably increase >93%. 

Also adding tests for `utils` will rise coverage above 95-97%

Think that's pretty reasonable

**Comment by zelima** [comment]
Test and coverage fix ups mentioned here moved to #90
