### ISSUE TITLE
[spec] graphql vs classic REST for API design

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#63]
Should we use graphql for our API design rather than classic REST?

/cc @pwalsh @subhankarb

**Comment by pwalsh** [comment]
I think for our queries which are not data rich/analytical it doesn't matter much

**Comment by Fak3** [comment]
Copying from hackpad, some brief research on graphql:

## Pros
* GET: client can query exactly what he needs:
```
{
Publisher {
    name,
    title,
    packages: {
        name, 
        bla bla
    }
 }
}
```

## Cons
* Server side implementation is quite complex (For flask see [graphene-sqlalchemy](https://github.com/graphql-python/graphene-sqlalchemy))
   * Introduces full-blown abstraction model over your (database) models, you will have to learn many new concepts (nodes, types, executors, ...). Quite non-DRY, no autogeneration magic I can find so far. 

* Create objects by request (called mutations in graphql) resembles RPC-style. Imho uglier than REST even from client side (subjective)

**Comment by pwalsh** [comment]
For our case of storing metadata, it is a total and complete overkill. Probably only of potential interest if we are actual reading data into a backend and then allowing queries across data packages.

**Comment by rufuspollock** [comment]
@pwalsh we are not planning to use it for POST / PUT but just for GET. It comes up in things like building the publisher page. I think we are agreed on defer for now.

**Comment by rufuspollock** [comment]
FIXED. Won't use graphql for now.
