### ISSUE TITLE
Read API for Package 

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/dpr-api#64]
I think this already partly implemented but wanted to check through all items:

```
/api/package/{publisher}/{name}
```

GET returns roughly the contents of the DB package table shorn of anything "private" (not sure we have anything at the moment):

```
id
name
publisher
readme
descriptor
...
```

QUESTION: should we use graphql approach - cf #63

**Comment by zelima** [comment]
@rgrp Can I have more clarifications on (for tests):
> shorn of anything "private"

What does this mean?

**Comment by rgrp** [comment]
@zelima private stuff would be something like an email address on a user. Often for the API we just taking a database object and turning it into json. When you do that you would want to check you are not pushing any private. With the Package object as it is at the moment I don't think we need to worry.

**Comment by zelima** [comment]
@rgrp Great, we don't revile anything private for now. Closing
