### ISSUE TITLE
Streaming for data proxy

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/dpr-api#69]
Currently data from S3 is first saved in memory https://github.com/frictionlessdata/dpr-api/blob/master/app/mod_api/controllers.py#L217 as string and after passed to response. This makes no sense of using streaming contents.
As it turned out streaming from s3 to flask is not that easy. I see two options:

-  Use approach described in this comment: https://github.com/boto/boto3/issues/426#issuecomment-184889230 (not sure how good it is)
-  Create/get permanent link from s3 where file lies and use https://github.com/frictionlessdata/tabulator-py to get stream using link to s3. 
   - problem is this returns list of csv rows. `[header1,header2],[value1,value2]` while we need to serve `header1,header2\nvalue1,value2`

**Comment by subhankarb** [comment]
WON'T FIX. 
We are loading data in dpr-js. So we are not using data stream in dpr-api.
