### ISSUE TITLE
Continuous Deployment of master code

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/dpr-api#86]
On every push we re-deploy site

* [x] Deploy site
* [x] Create fixture sysadmin user
* [x] Locate and download fixture data (scripted)
  * [x] One nice simple data package (can use local fixtures data for now)
  * [ ] One with a lot of data in it so we can test performance of graphs etc
  * [ ] One with local data and one with remote
* [x] Push a sample data package or two using sysadmin user (scripted)

**Comment by zelima** [comment]
@rgrp @subhankarb Can we close this one as we are using local fixtures data for now and reopen/open new for next sprint?

**Comment by rgrp** [comment]
@zelima yes we can close this now if you have reviewed the PR and are happy.

**Comment by rgrp** [comment]
FIXED. The extra fixture data loading was optional and can be done later ...
