### ISSUE TITLE
[signup] Local "on new user" actions

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/dpr-api#9]
Handle callback from external auth provider and perform "on new user" actions
- [x] Create user object in local DB
- [x] Generate user secret for user in CLI etc
- [x] Create publisher and associate user as owner - #66 plus create as part of signup
  - Publisher created with name of the user name
  - Association created with role 'owner'
- [x] Issue them a token so they are signed in

**Comment by subhankarb** [comment]
Finished
